### ISSUE TITLE
Enlace roto en el admin (si WP no está en la raíz)

### ISSUE THREAD

**Issue by ciudadanoB** [closemarketing/woocommerce-es-OLD#1]
Buenas, una tontería que no urge lo más mínimo!

En el includes/class-admin.php, línea 197, hay una llamada directa al /wp-admin/admin.php?page=wces-addons en un enlace, y es un 404 en el caso de que tengas WordPress instalado en una carpeta en lugar de en la raíz. Supongo que hay que añadir la constante que te dice dónde está instalado WP en lugar de engancharlo a pelo.

Pero a ver si os vais a quedar sin vender por eso :P

**Comment by davidperezgar** [comment]
Hey! Muchas gracias por avisar! Lo preparamos para,la,próxima versión! Gracias!

**Comment by davidperezgar** [comment]
Arreglado en versión 2.0.2
