### ISSUE TITLE
Fix fatal error related with the VAT Number injection in PDF Invoices

### ISSUE THREAD

**Issue by YordanSoares** [closemarketing/woocommerce-es-OLD#2]
Currently, the plugin is producing a fatal error in PDF Invoices generated with [PDF Invoices & Packing Slips for WooCommerce](https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/). This is because the `$wpo_wcpdf` global variable is no longer available since v3.6.3 (see [changelog](https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/#developers)).

**Comment by davidperezgar** [comment]
Ok Yordan, thanks for the issue. I'll check it out the PR.
